name: Cypress snapshot update

on:
  workflow_dispatch:
  schedule:
    # At 2:30 on Sundays
    - cron: '20 1 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branches: ["main", "master", "stable27", "stable26", "stable25"]
  
    name: cypress-snapshot-update-${{ matrix.branches }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ matrix.branches }}

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1 # v2.2
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^7'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Snapshot update
        run: npm run cypress:update-snapshots

      - name: Create Pull Request
        if: always()
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: "chore(deps): cypress snapshot update"
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: automated/noid/${{ matrix.branches }}-cypress-snapshot-update
          title: "[${{ matrix.branches }}] Update cypress snapshots"
          body: |
            Auto-generated update of cypress snapshots
          labels: |
            dependencies
            3. to review
          add-paths: |
            cypress/snapshots
